---
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
      - --args=--anchor=false
      - --args=--html=false
      - --args=--hide=modules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
